# ============================================================
# Profil lokalny ? nadpisuje ustawienia z application.properties
# Ten plik NIE powinien trafi? na GitHuba (dodaj do .gitignore)
# ============================================================

spring.datasource.url=jdbc:mysql://localhost:3306/fx-rate-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# MariaDB ? nadpisuje MySQLDialect z application.properties
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

